### ISSUE TITLE
我司目前的项目使用Carthage进行依赖管理

### ISSUE THREAD

**Issue by zongren** [beecloud/beecloud-ios#52]
请问如何配置，只需要支付宝和微信

**Comment by Ewenlong03** [comment]
仔细阅读 readme.md 开发文档，有不明白的地方，可以再联系我们，谢谢！



———————
Best regards,
Ewen 黄文龙

产品经理

苏州比可网络科技有限公司

移动电话：+8618654155015

座        机:  0512-86861620

网        站：https://beecloud.cn

地        址：江苏省苏州市工业园区若水路388号纳米大学科技园E1006



发件人:  宗仁 <notifications@github.com>
答复:  beecloud/beecloud-ios <reply@reply.github.com>
日期:  2016年12月26日 星期一 下午9:02
至:  beecloud/beecloud-ios <beecloud-ios@noreply.github.com>
抄送:  Subscribed <subscribed@noreply.github.com>
主题:  [beecloud/beecloud-ios] 我司目前的项目使用Carthage进行依赖管理 (#52)


请问如何配置，只需要支付宝和微信

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/beecloud/beecloud-ios","title":"beecloud/beecloud-ios","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/beecloud/beecloud-ios"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"我司目前的项目使用Carthage进行依赖管理 (#52)"}],"action":{"name":"View Issue","url":"https://github.com/beecloud/beecloud-ios/issues/52"}}}

**Comment by zongren** [comment]
你好，已经按照文档说明，直接把源码拖到项目中，目前使用正常
